className = input("in something");

s2 =  ""
s2 += "module game\n"
s2 += "{\n"
s2 += "    export class " + className + "Data extends DataBase\n"
s2 += "    {\n"
s2 += "        public Destroy()\n"
s2 += "        {\n"
s2 += "            super.Destroy();\n"
s2 += "        }\n"
s2 += "\n"
s2 += "        public PackData()\n"
s2 += "        {\n"
s2 += "            return this;\n"
s2 += "        }\n"
s2 += "    }\n"
s2 += "\n"
s2 += "    export class " + className + " extends ItemRenderBase\n"
s2 += "    {\n"
s2 += "        public info:" + className + "Data;\n"
s2 += "        public constructor()\n"
s2 += "        {\n"
s2 += "            super('" + className + "Skin');\n"
s2 += "        }\n"
s2 += "\n"
s2 += "        public dataChanged()\n"
s2 += "        {\n"
s2 += "            if(this.data == null)\n"
s2 += "                return;\n"
s2 += "            this.info = this.data;\n"
s2 += "        }\n"
s2 += "\n"
s2 += "        protected Destroy()\n"
s2 += "        {\n"
s2 += "            if(this.info != null)\n"
s2 += "                this.info.Destroy();\n"
s2 += "        }\n"
s2 += "    }\n"
s2 += "}\n"

classFileName = "C:/Users/User/Desktop/" + className + ".ts";
with open(classFileName, "w", encoding="utf-8") as f:
	f.write(s2);

